apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-argo
  namespace: produccion
  labels:
    app: hello-node-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node-argo
  template:
    metadata:
      labels:
        app: hello-node-argo
    spec:
      containers:
      - name: hello-node-argo
        image: gcr.io/jenkins-servinformacion/clase3_pipeline:41
        ports:
        - containerPort: 8888
