apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "chiper"
  namespace: "default"
  labels:
    app: "chiper"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "chiper"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: "memory"
      targetAverageUtilization: 60
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
